// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OzPsqbJCEpBAk_k8IiRzEcWceemTc8U',
    appId: '1:501579157196:web:8b33d122e1b6c6172f7c69',
    messagingSenderId: '501579157196',
    projectId: 'shoeapp-83928',
    authDomain: 'shoeapp-83928.firebaseapp.com',
    storageBucket: 'shoeapp-83928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQuzSdiCLr6Ah2vgcp8U4NMIWvYjLIkfc',
    appId: '1:501579157196:android:1f1f448a7b5f4b622f7c69',
    messagingSenderId: '501579157196',
    projectId: 'shoeapp-83928',
    storageBucket: 'shoeapp-83928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMbdcqLAnEP1_VcmE1AI-F9YrW9KjxD8',
    appId: '1:501579157196:ios:6689cb57f4e6e30b2f7c69',
    messagingSenderId: '501579157196',
    projectId: 'shoeapp-83928',
    storageBucket: 'shoeapp-83928.appspot.com',
    iosBundleId: 'com.example.sheoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMbdcqLAnEP1_VcmE1AI-F9YrW9KjxD8',
    appId: '1:501579157196:ios:a35ea6dc6aace1632f7c69',
    messagingSenderId: '501579157196',
    projectId: 'shoeapp-83928',
    storageBucket: 'shoeapp-83928.appspot.com',
    iosBundleId: 'com.example.sheoapp.RunnerTests',
  );
}
